version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=device-db
    ports:
      - '5433:5432'

  devices:
    container_name: device_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8089:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/device-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
